version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: app_php
    volumes:
      - ./app:/var/www/html/
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db
    environment:
      - PHP_EXTENSION_DIR=/usr/local/lib/php/extensions/no-debug-non-zts-20220829
    working_dir: /var/www/html/
    restart: always

  db:
    image: mariadb:10.5
    container_name: app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${DB_VOLUME_NAME}:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
    name: ${DB_VOLUME_NAME}
