services:
  php:
    image: douae01/php_app:latest
    container_name: app_php
    volumes: 
      - ./app:/var/www/html/
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PHP_EXTENSION_DIR=/usr/local/lib/php/extensions/no-debug-non-zts-20220829
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    working_dir: /var/www/html/
    restart: always

  db:
    image: mariadb:10.5
    container_name: app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      #sauvegarde toutes les donn√©es de DB dans un volume
      - ${DB_VOLUME_NAME}:/var/lib/mysql
      - ./docker/mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
    name: ${DB_VOLUME_NAME}
